# Generated by Django 5.0 on 2025-04-07 15:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da atividade', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('observacoes', models.CharField(blank=True, help_text='Insira as observações', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Observações')),
                ('data', models.DateField()),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de Trilhas', 'Corrida de Trilhas'), ('Treino de Bicicleta', 'Treino de Bicicleta'), ('Caminhada', 'Caminhada'), ('Treino de Alta Intensidade', 'Treino de Alta Intensidade'), ('Treino de Força', 'Treino de Força'), ('Treino Aeróbico', 'Treino Aeróbico'), ('Natação', 'Natação')], help_text='Selecione o tipo de esporte', max_length=50, verbose_name='Tipo de esporte')),
                ('inicio', models.TimeField()),
                ('duracao', models.DurationField()),
                ('distancia', models.FloatField()),
                ('ritmo', models.TimeField()),
                ('calorias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('elevacao_total', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do clube', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome')),
                ('local', models.CharField(help_text='Insira o local do clube', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Local')),
                ('pais', models.CharField(help_text='Insira o país do clube', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='País')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de Trilhas', 'Corrida de Trilhas'), ('Treino de Bicicleta', 'Treino de Bicicleta'), ('Caminhada', 'Caminhada'), ('Treino de Alta Intensidade', 'Treino de Alta Intensidade'), ('Treino de Força', 'Treino de Força'), ('Treino Aeróbico', 'Treino Aeróbico'), ('Natação', 'Natação')], help_text='Selecione o tipo de esporte', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Tipo de esporte')),
                ('biografia', models.TextField(blank=True, help_text='Insira a biografia', null=True, verbose_name='Biografia')),
                ('url', models.URLField(help_text='Insira a URL', max_length=150, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do equipamento', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('marca', models.CharField(help_text='Insira a marca do equipamento', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Insira o modelo do equipamento', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo')),
                ('apelido', models.CharField(help_text='Insira o apelido do equipamento', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apelido')),
                ('tipo_equipamento', models.CharField(choices=[('Tênis', 'Tênis'), ('Bicicleta', 'Bicicleta'), ('Dispositivo_inteligente', 'Dispositivo Inteligente')], help_text='Selecione o seu tipo de equipamento', max_length=50, verbose_name='Tipo de equipamento')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de Trilhas', 'Corrida de Trilhas'), ('Treino de Bicicleta', 'Treino de Bicicleta'), ('Caminhada', 'Caminhada'), ('Treino de Alta Intensidade', 'Treino de Alta Intensidade'), ('Treino de Força', 'Treino de Força'), ('Treino Aeróbico', 'Treino Aeróbico'), ('Natação', 'Natação')], help_text='Selecione o tipo de esporte', max_length=50, verbose_name='Tipo de esporte')),
                ('distancia_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('distancia_prevista', models.IntegerField(validators=[django.core.validators.MinValueValidator(400)])),
                ('peso', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Insira seu Email', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Email')),
                ('nome', models.CharField(help_text='Insira seu nome', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Insira seu CPF', max_length=11, verbose_name='CPF')),
                ('senha', models.CharField(help_text='Insira sua senha', max_length=20, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Senha')),
                ('data_nascimento', models.DateField(help_text='Qual sua data de nascimento?', verbose_name='Data de nascimento')),
                ('local', models.CharField(help_text='Insira seu local', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Local')),
                ('pais', models.CharField(help_text='Insira seu País', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='País')),
                ('genero', models.CharField(choices=[('Homem', 'Homem'), ('Mulher', 'Mulher'), ('Não binário', 'Não binário'), ('Não informado', 'Não informado')], help_text='Selecione o seu gênero', max_length=20, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Gênero')),
                ('peso', models.FloatField(blank=True, default=0.0, help_text='Insira seu peso', null=True, validators=[django.core.validators.MinValueValidator(20)], verbose_name='Peso')),
                ('pagina_pessoal', models.URLField(help_text='Insira sua URL', max_length=150, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='URL')),
                ('biografia', models.TextField(blank=True, help_text='Insira sua biografia', null=True, verbose_name='Biografia')),
                ('premium', models.BooleanField(default=False)),
                ('membro_desde', models.DateField(default=datetime.date(2025, 4, 7))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para o Recorde', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('tipo_marca', models.CharField(choices=[('100M', '100 Metros'), ('400M', '400 Metros'), ('1KM', '1 Quilômetro'), ('5KM', '5 Quilômetros'), ('10KM', '10 Quilômetros'), ('15KM', '15 Quilômetros'), ('20KM', '20 Quilômetros'), ('Meia Maratona', 'Meia Maratona'), ('30KM', '30 Quilômetros'), ('Maratona', 'Maratona'), ('Longa Distância', 'Longa Distância'), ('Longa Duração', 'Longa Duração')], help_text='Selecione o tipo de marca.', max_length=20, verbose_name='Tipo marca')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de Trilhas', 'Corrida de Trilhas'), ('Treino de Bicicleta', 'Treino de Bicicleta'), ('Caminhada', 'Caminhada'), ('Treino de Alta Intensidade', 'Treino de Alta Intensidade'), ('Treino de Força', 'Treino de Força'), ('Treino Aeróbico', 'Treino Aeróbico'), ('Natação', 'Natação')], help_text='Selecione o tipo de esporte', max_length=30, verbose_name='Tipo de esporte')),
                ('ritmo', models.TimeField(verbose_name='Ritmo')),
                ('duracao', models.DurationField(verbose_name='Duração')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
